_target_: audyn.criterion.base.MultiCriteria
nll:
  _target_: audyn.criterion.base.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.flow.NLLLoss
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      logdet: logdet
      num_elements: num_elements
    target:
