[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "Audyn"
authors = [
    {name = "Takuya Hasumi"},
]
description = "A PyTorch toolkit for audio synthesis."
readme = "README.md"
license = {file = "LICENSE"}
urls = {url = "https://github.com/tky823/Audyn"}
requires-python = ">=3.8, <4"
dependencies = [
    "torch",
    "torchaudio",
]
dynamic = [
    "version",
]

[project.optional-dependencies]
dev = [
    "flake8",
    "black",
    "isort"
]

[tool.setuptools.dynamic]
version = {attr = "audyn.__version__"}

[tool.setuptools.packages.find]
include = [
    "audyn",
]

[tool.black]
line-length = 99

[tools.flake8]
max-line-length = 99

[tool.isort]
profile = "black"
line_length = 99
