defaults:
  - record: wavenet
  - dataset: sortable-torch
  - dataloader: sequential-batch
  - _self_

dataset:
  train:
    sort_key: waveform

dataloader:
  train:
    batch_size: 4
  validation:
    batch_size: 1

key_mapping:
  train:
    input:
      input: waveform_slice_mulaw
      local_conditioning: log_melspectrogram_slice
    output: estimated_waveform_slice_mulaw
  validation: ${.train}
  inference:
    input:
      initial_state: initial_waveform_mulaw
      local_conditioning: ${...train.input.local_conditioning}
      max_length: max_waveform_slice_length
    output: estimated_waveform_slice_mulaw

clip_gradient:
  _target_: audyn.utils.GradClipper
  mode: norm
  max_norm: 1

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 5
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 5
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs:
  iterations: 10
  lr_scheduler: iteration
