defaults:
  - dataset: sortable-torch
  - dataloader: sequential-batch
  - record: fastspeech
  - _self_

dataset:
  train:
    sort_key: waveform

dataloader:
  train:
    batch_size: 64
  validation:
    batch_size: 1

key_mapping:
  train:
    input:
      src: phones
      duration: duration
    output:
      - estimated_melspectrogram
      - estimated_duration
  validation: ${.train}

clip_gradient:
  _target_: audyn.utils.GradClipper
  mode: norm
  max_norm: 1

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 10000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 100
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs:
  iterations: 80000
  lr_scheduler: iteration
