defaults:
  - record: defaults
  - _self_

dataset:
  train:
    _target_: torch.utils.data.Dataset
    dataset:
  validation:
    _target_: torch.utils.data.Dataset
    dataset:

dataloader:
  train:
    _target_: torch.utils.data.DataLoader
    batch_size:
    shuffle: true
    seed: ${system.seed}
  validation:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    shuffle: false
    seed: ${system.seed}

key_mapping:
  train:
    generator:
      input:
        noise: noise
      output: fake
    discriminator:
      fake:
        input:
          waveform: ${....generator.output}
        output: fake_prob
      real:
        input:
          waveform: input
        output: real_prob
  validation: ${.train}

clip_gradient:

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 20000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 100
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs:
  iterations: 100000
  lr_scheduler:
    generator: iteration
    discriminator: iteration
