generator:
  - name: adamw
    optimizer:
      _target_: torch.optim.Adam
      lr: 1.0e-4
      betas:
        - 0.5
        - 0.9
    modules:
      - encoder
      - decoder
  - name: ema
    optimizer:
      _target_: audyn.optim.optimizer.ExponentialMovingAverageCodebookOptimizer
      smooth: 0.99
      reset_step: 20
    modules:
      - vector_quantizer
discriminator:
  _target_: torch.optim.Adam
  lr: 1.0e-4
  betas:
    - 0.5
    - 0.9
