generator:
  - name: adamw
    optimizer:
      _target_: torch.optim.AdamW
      lr: 2.0e-4
      betas:
        - 0.8
        - 0.99
    modules:
      - encoder
      - decoder
  - name: ema
    optimizer:
      _target_: audyn.optim.optimizer.ExponentialMovingAverageCodebookOptimizer
      smooth: 0.999
    modules:
      - vector_quantizer
discriminator:
  _target_: torch.optim.AdamW
  lr: 2.0e-4
  betas:
    - 0.8
    - 0.99
