_target_: utils.models.clap.CLAP
text_tower:
  _target_: utils.models.clap.TextTransformerTower.build_from_pretrained
  path: ???
  aggregation: pool
  out_channels: 128
audio_tower:
  _target_: utils.models.clap.AudioTransformerTower.build_from_pretrained
  path: ???
  aggregation: pool
  out_channels: ${..text_tower.out_channels}
