_target_: utils.models.transformer.TextTransformerMaskedLanguageModel
backbone:
  _target_: utils.models.transformer.TextTransformerMaskedLanguageModelBackbone
  vocab_size: ${const:audyn.utils.data.clotho.vocab_size}
  embedding_dim: 64
  nhead: 2
  num_layers: 2
  batch_first: true
  mask_index: ${data.text.mask_index}
  ignore_index: ${data.text.ignore_index}
  selection_rate: ${data.text.selection_rate}
  mask_rate: ${data.text.mask_rate}
  replace_rate: ${data.text.replace_rate}
out_proj:
  _target_: torch.nn.Linear
  in_features: ${..backbone.embedding_dim}
  out_features: ${const:audyn.utils.data.clotho.vocab_size}
