_target_: audyn.models.waveglow.WaveGlow
in_channels: 1
hidden_channels: 16
skip_channels: 8
num_flows: 3
num_stacks: 2
num_layers: 2
num_groups: 8
early_size: 2
kernel_size: 3
bias: true
is_causal: false
conv: gated
upsample:
  _target_: audyn.models.wavenet.Upsample
  in_channels: ${data.melspectrogram.n_mels}
  out_channels: ${.in_channels}
  kernel_size: ${data.melspectrogram.n_fft}
  stride: ${data.melspectrogram.hop_length}
local_dim: ${data.melspectrogram.n_mels}
weight_norm: true
