defaults:
  - dataset: sortable-torch
  - dataloader: sequential-batch
  - key_mapping: glowtts_ljspeech
  - record: glowtts
  - _self_

dataset:
  train:
    sort_key: waveform

dataloader:
  train:
    batch_size: 32
  validation:
    batch_size: 1

clip_gradient:
  _target_: audyn.utils.GradClipper
  mode: norm
  max_norm: 5

ddp_kwargs:

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 200000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 2000
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs: 10000
  iterations:
  lr_scheduler:
