defaults:
  - record: soundstream
  - dataset: torch
  - dataloader: defaults
  - key_mapping: soundstream_waveform_discriminator
  - _self_

dataloader:
  train:
    batch_size: 32
  validation:
    batch_size: 32

clip_gradient:
  generator:
    _target_: audyn.utils.GradClipper
    mode: norm
    max_norm: 10
  discriminator: ${.generator}

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 5000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 20
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs:
  iterations: 200000
  lr_scheduler:
    generator:
    discriminator:
