- name: text
  lr_scheduler:
    _target_: audyn.optim.lr_scheduler.TransformerLRScheduler
    d_model: ${model.text_tower.backbone.embedding_dim}
    warmup_steps: 10
- name: audio
  lr_scheduler:
    _target_: ${...0.lr_scheduler._target_}
    d_model: ${model.audio_tower.backbone.embedding_dim}
    warmup_steps: ${...0.lr_scheduler.warmup_steps}
