_target_: torch.optim.lr_scheduler.LambdaLR
lr_lambda:
  _target_: utils.lr_scheduler.ExponentialWarmupLinearCooldownLambda
  warmup_steps: 5
  constant_steps: 15
  cooldown_steps: 20
  last_factor: 1.0e-2
