defaults:
  - record: hifigan
  - _self_

dataset:
  train:
    _target_: audyn.utils.data.dataset.SortableTorchObjectDataset
    list_path:
    feature_dir:
    sort_key: waveform
  validation:
    _target_: audyn.utils.data.dataset.TorchObjectDataset
    list_path:
    feature_dir:

dataloader:
  train:
    _target_: audyn.utils.data.SequentialBatchDataLoader
    batch_size: 16
    shuffle: true
    seed: ${system.seed}
  validation:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    shuffle: false

key_mapping:
  train:
    generator:
      input:
        input: log_melspectrogram_slice
      output: estimated_waveform_slice
    discriminator:
      real:
        input:
          input: waveform_slice
        output:
          - - period_real_prob
            - scale_real_prob
          - - period_real_feature_map
            - scale_real_feature_map
      fake:
        input:
          input: ${....generator.output}
        output:
          - - period_fake_prob
            - scale_fake_prob
          - - period_fake_feature_map
            - scale_fake_feature_map
  validation: ${.train}
  inference:
    generator:
      input:
        input: log_melspectrogram
      output: estimated_waveform

clip_gradient:
  generator:
    _target_: audyn.utils.GradClipper
    mode: norm
    max_norm: 10
  discriminator: ${.generator}

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 200000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 1000
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs: 3100
  iterations:
  lr_scheduler:
    generator: epoch
    discriminator: epoch
