generator:
  _target_: audyn.criterion.base.MultiCriteria
  codebook_loss:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.rvqvae.CodebookLoss
      layer_wise: true
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        encoded: encoded
        quantized: quantized
      target:
  commitment_loss:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.rvqvae.CommitmentLoss
      layer_wise: true
      reduction: mean
    weight: 0.25
    key_mapping:
      estimated:
        encoded: encoded
        quantized: quantized
      target:
  waveform_fm:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.FeatureMatchingLoss
    weight: 2
    key_mapping:
      estimated:
        input: waveform_fake_feature_map
        target: waveform_real_feature_map
      target:
  spectrogram_fm:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.FeatureMatchingLoss
    weight: 2
    key_mapping:
      estimated:
        input: spectrogram_fake_feature_map
        target: spectrogram_real_feature_map
      target:
  waveform_adversarial:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.DiscriminatorHingeLoss
      minimize: false
      margin: 1
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: waveform_fake_prob
      target:
  spectrogram_adversarial:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.DiscriminatorHingeLoss
      minimize: false
      margin: 1
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: spectrogram_fake_prob
      target:
discriminator:
  _target_: audyn.criterion.base.MultiCriteria
  waveform_discriminator_fake:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.DiscriminatorHingeLoss
      minimize: true
      margin: ${....generator.waveform_adversarial.criterion.margin}
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: waveform_fake_prob
      target:
  waveform_discriminator_real:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.DiscriminatorHingeLoss
      minimize: false
      margin: ${....generator.waveform_adversarial.criterion.margin}
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: waveform_real_prob
      target:
  spectrogram_discriminator_fake:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.DiscriminatorHingeLoss
      minimize: true
      margin: ${....generator.spectrogram_adversarial.criterion.margin}
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: spectrogram_fake_prob
      target:
  spectrogram_discriminator_real:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.DiscriminatorHingeLoss
      minimize: false
      margin: ${....generator.spectrogram_adversarial.criterion.margin}
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: spectrogram_real_prob
      target:
