_target_: audyn.criterion.base.MultiCriteria
cross_entropy:
  _target_: audyn.criterion.base.BaseCriterionWrapper
  criterion:
    _target_: utils.criterion.cross_entropy.VALLECrossEntropyLoss
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: logit
    target:
      target: codebook_indices
