_target_: audyn.criterion.base.MultiCriteria
cross_entropy:
  _target_: audyn.criterion.base.BaseCriterionWrapper
  criterion:
    _target_: utils.criterion.MaskedLaguageModelCrossEntropyLoss
    ignore_index: ${data.text.ignore_index}
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: log_probs
      target: target_text
    target:
      length: text_length
