waveform:
  iteration:
    every: 100
    sample_size: 1
    key_mapping:
      output:
        estimated_waveform_slice_mulaw: "Estimated waveform (iteration)"
      reference:
        waveform_slice_mulaw: "Waveform (iteration)"
    transforms:
      output:
        estimated_waveform_slice_mulaw:
          _target_: torchvision.transforms.Compose
          _args_:
            - - _target_: torch.argmax
                _partial_: true
                _convert_: partial
                dim: 0
              - _target_: torchaudio.transforms.MuLawDecoding
                quantization_channels: ${data.audio.quantization_channels}
      reference:
        waveform_slice_mulaw:
          _target_: torchaudio.transforms.MuLawDecoding
          quantization_channels: ${data.audio.quantization_channels}
  epoch:
    every: 1
    sample_size: 1
    key_mapping:
      validation:
        output:
          estimated_waveform_slice_mulaw: "Estimated waveform (epoch)"
        reference:
          waveform_slice_mulaw: "Waveform (epoch)"
      inference:
        output:
          estimated_waveform_slice_mulaw: "Estimated waveform of inference (epoch)"
        reference:
          waveform_slice_mulaw: "Waveform of inference (epoch)"
    transforms:
      validation: ${...iteration.transforms}
      inference:
        output:
          estimated_waveform_slice_mulaw:
            _target_: torchaudio.transforms.MuLawDecoding
            quantization_channels: ${data.audio.quantization_channels}
        reference:
          waveform_slice_mulaw:
            _target_: torchaudio.transforms.MuLawDecoding
            quantization_channels: ${data.audio.quantization_channels}
audio:
  iteration:
    every: 100
    sample_size: 1
    sample_rate: ${data.audio.sample_rate}
    key_mapping:
      output:
        estimated_waveform_slice_mulaw: "Estimated audio (iteration)"
      reference:
        waveform_slice_mulaw: "Audio (iteration)"
    transforms: ${...waveform.iteration.transforms}
  epoch:
    every: 1
    sample_size: 1
    sample_rate: ${data.audio.sample_rate}
    key_mapping:
      validation:
        output:
          estimated_waveform_slice_mulaw: "Estimated audio (epoch)"
        reference:
          waveform_slice_mulaw: "Audio (epoch)"
      inference:
        output:
          estimated_waveform_slice_mulaw: "Estimated audio of inference (epoch)"
        reference:
          waveform_slice_mulaw: "Audio of inference (epoch)"
    transforms: ${...waveform.epoch.transforms}
