defaults:
  - record: waveglow
  - _self_

dataset:
  train:
    _target_: audyn.utils.data.dataset.SortableTorchObjectDataset
    list_path:
    feature_dir:
    sort_key: waveform
  validation:
    _target_: audyn.utils.data.dataset.TorchObjectDataset
    list_path:
    feature_dir:

dataloader:
  train:
    _target_: audyn.utils.data.SequentialBatchDataLoader
    batch_size: 24
    shuffle: true
    seed: ${system.seed}
  validation:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    shuffle: false
    seed: ${system.seed}

key_mapping:
  train:
    input:
      input: waveform_slice
      local_conditioning: log_melspectrogram_slice
      logdet: zeros
    output:
      - latent
      - logdet
  validation: ${.train}
  inference:
    input:
      input: noise
      local_conditioning: log_melspectrogram
    output: estimated_waveform

clip_gradient:
  _target_: torch.nn.utils.clip_grad_norm_
  max_norm: 1

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 200000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 1000
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs:
  iterations: 580000
  lr_scheduler: iteration
